// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function loop(_digits, _prev, _sum) {
  while(true) {
    var sum = _sum;
    var prev = _prev;
    var digits = _digits;
    if (digits) {
      var current = digits[0];
      var match = +(current === prev);
      _sum = match !== 0 ? sum + current | 0 : sum;
      _prev = current;
      _digits = digits[1];
      continue ;
      
    } else {
      return sum;
    }
  };
}

function captcha(digits) {
  if (digits && digits[1]) {
    return loop(List.rev(digits), digits[0], 0);
  } else {
    return 0;
  }
}

exports.loop    = loop;
exports.captcha = captcha;
/* No side effect */
