// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function checksum(spreadsheet) {
  return List.fold_left((function (acc, cur) {
                return acc + (
                        cur ? List.fold_left((function (acc2, cur2) {
                                  var match = +(cur2 > acc2);
                                  if (match !== 0) {
                                    return cur2;
                                  } else {
                                    return acc2;
                                  }
                                }), 0, cur) - List.fold_left((function (acc2, cur2) {
                                  var match = +(cur2 < acc2);
                                  if (match !== 0) {
                                    return cur2;
                                  } else {
                                    return acc2;
                                  }
                                }), Pervasives.max_int, cur) | 0 : 0
                      ) | 0;
              }), 0, spreadsheet);
}

exports.checksum = checksum;
/* No side effect */
