// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function loop(instructions, _idx, _count) {
  while(true) {
    var count = _count;
    var idx = _idx;
    var nextIdx = idx + Caml_array.caml_array_get(instructions, idx) | 0;
    if (nextIdx < 0 || (nextIdx + 1 | 0) > instructions.length) {
      return count;
    } else {
      Caml_array.caml_array_set(instructions, idx, Caml_array.caml_array_get(instructions, idx) + 1 | 0);
      _count = count + 1 | 0;
      _idx = nextIdx;
      continue ;
      
    }
  };
}

function stepsToExit(instructions) {
  if (instructions.length !== 0) {
    return loop(instructions, 0, 1);
  } else {
    return -1;
  }
}

exports.loop        = loop;
exports.stepsToExit = stepsToExit;
/* No side effect */
