// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                  = require("bs-jest/src/jest.js");
var Day1$ReasonAdvent2017 = require("../src/day1.bs.js");

describe("Day 1", (function () {
        Jest.test("1122", (function () {
                return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](Day1$ReasonAdvent2017.captcha(/* :: */[
                                    1,
                                    /* :: */[
                                      1,
                                      /* :: */[
                                        2,
                                        /* :: */[
                                          2,
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("1111", (function () {
                return Jest.Expect[/* toBe */2](4)(Jest.Expect[/* expect */0](Day1$ReasonAdvent2017.captcha(/* :: */[
                                    1,
                                    /* :: */[
                                      1,
                                      /* :: */[
                                        1,
                                        /* :: */[
                                          1,
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("1234", (function () {
                return Jest.Expect[/* toBe */2](0)(Jest.Expect[/* expect */0](Day1$ReasonAdvent2017.captcha(/* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* :: */[
                                          4,
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        return Jest.test("91212129", (function () {
                      return Jest.Expect[/* toBe */2](9)(Jest.Expect[/* expect */0](Day1$ReasonAdvent2017.captcha(/* :: */[
                                          9,
                                          /* :: */[
                                            1,
                                            /* :: */[
                                              2,
                                              /* :: */[
                                                1,
                                                /* :: */[
                                                  2,
                                                  /* :: */[
                                                    1,
                                                    /* :: */[
                                                      2,
                                                      /* :: */[
                                                        9,
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ])));
                    }));
      }));

/*  Not a pure module */
