// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                  = require("bs-jest/src/jest.js");
var Day3$ReasonAdvent2017 = require("../src/day3.bs.js");

describe("Day 3", (function () {
        Jest.test("1", (function () {
                return Jest.Expect[/* toBe */2](0)(Jest.Expect[/* expect */0](Day3$ReasonAdvent2017.distance(1)));
              }));
        Jest.test("12", (function () {
                return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](Day3$ReasonAdvent2017.distance(12)));
              }));
        Jest.test("23", (function () {
                return Jest.Expect[/* toBe */2](2)(Jest.Expect[/* expect */0](Day3$ReasonAdvent2017.distance(23)));
              }));
        return Jest.test("312051", (function () {
                      return Jest.Expect[/* toBe */2](430)(Jest.Expect[/* expect */0](Day3$ReasonAdvent2017.distance(312051)));
                    }));
      }));

/*  Not a pure module */
