// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                  = require("bs-jest/src/jest.js");
var Day4$ReasonAdvent2017 = require("../src/day4.bs.js");

describe("Day 4", (function () {
        Jest.test("aa bb cc dd ee", (function () {
                return Jest.Expect[/* toBe */2](/* true */1)(Jest.Expect[/* expect */0](Day4$ReasonAdvent2017.isValidPassphrase("aa bb cc dd ee")));
              }));
        Jest.test("aa bb cc dd aa", (function () {
                return Jest.Expect[/* toBe */2](/* false */0)(Jest.Expect[/* expect */0](Day4$ReasonAdvent2017.isValidPassphrase("aa bb cc dd aa")));
              }));
        return Jest.test("aa bb cc dd aaa", (function () {
                      return Jest.Expect[/* toBe */2](/* true */1)(Jest.Expect[/* expect */0](Day4$ReasonAdvent2017.isValidPassphrase("aa bb cc dd aaa")));
                    }));
      }));

/*  Not a pure module */
